-- MySQL Script generated by MySQL Workbench
-- Thu May 27 16:08:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema board4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema board4
-- -----------------------------------------------------
drop database board4;
CREATE SCHEMA IF NOT EXISTS `board4` ;
USE `board4` ;

-- -----------------------------------------------------
-- Table `board4`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `board4`.`member` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `post` CHAR(5) NULL,
  `address` VARCHAR(45) NULL,
  `detailaddress` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  `rdate` TIMESTAMP NULL DEFAULT current_timestamp,
  `state` VARCHAR(10) NULL,
  PRIMARY KEY (`no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `board4`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `board4`.`board` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `contents` VARCHAR(45) NULL,
  `wdate` TIMESTAMP NULL default current_timestamp,
  `views` INT NOT NULL DEFAULT 0,
  `writer` INT NOT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_board__idx` (`writer` ASC) ,
  CONSTRAINT `fk_board_`
    FOREIGN KEY (`writer`)
    REFERENCES `board4`.`member` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into member(name,post,address,detailaddress,email,tel,password,id)
values('이학명','11111','address1','detailaddress1','eamil1@naver.com','01000000000','1234','leehm');
insert into member(name,post,address,detailaddress,email,tel,password,id)
values('성상현','11111','address1','detailaddress1','eamil1@naver.com','01000000000','1234','ssh');
insert into member(name,post,address,detailaddress,email,tel,password,id)
values('임영웅','11111','address1','detailaddress1','eamil1@naver.com','01000000000','1234','lyy');
insert into member(name,post,address,detailaddress,email,tel,password,id)
values('유인홍','11111','address1','detailaddress1','eamil1@naver.com','01000000000','1234','yih');
insert into board(title,contents,writer)values('title1','content1',1);
insert into board(title,contents,writer)values('title2','content2',1);
insert into board(title,contents,writer)values('title3','content3',1);
select*from member;
select*from board;