-- MySQL Script generated by MySQL Workbench
-- Wed Jun 16 12:49:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mvc3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mvc3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mvc3` ;
USE `mvc3` ;

-- -----------------------------------------------------
-- Table `mvc3`.`memeber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc3`.`memeber` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `profile` blob,
  `post` CHAR(5) NULL,
  `address` VARCHAR(45) NULL,
  `detailaddress` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  `rdate` TIMESTAMP(12) NULL DEFAULT current_timestamp,
  `state` VARCHAR(10) NULL,
  `gender` CHAR(5) ,
  PRIMARY KEY (`no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvc3`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc3`.`board` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `contents` VARCHAR(45) NULL,
  `wdate` TIMESTAMP(12) NULL current_timestamp,
  `views` INT NOT NULL DEFAULT 0,
  `writer` INT NOT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_board__idx` (`writer` ASC) ,
  CONSTRAINT `fk_board_`
    FOREIGN KEY (`writer`)
    REFERENCES `mvc3`.`memeber` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvc3`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc3`.`comment` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `contents` VARCHAR(45) NOT NULL,
  `wdate` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `board_no` INT NOT NULL,
  `writer` INT NOT NULL,
  PRIMARY KEY (`no`),
  INDEX `fk_comment_board1_idx` (`board_no` ASC),
  INDEX `fk_comment_memeber1_idx` (`writer` ASC),
  CONSTRAINT `fk_comment_board1`
    FOREIGN KEY (`board_no`)
    REFERENCES `mvc3`.`board` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_memeber1`
    FOREIGN KEY (`writer`)
    REFERENCES `mvc3`.`memeber` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
