-- MySQL Script generated by MySQL Workbench
-- Tue Jun 22 17:17:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE `mvc3` ;

-- -----------------------------------------------------
-- Table `mvc3`.`chatmember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc3`.`chatmember` (
  `no` INT NOT NULL AUTO_INCREMENT,
  `member_no` INT NOT NULL,
  `roomName` VARCHAR(50) NOT NULL,
  INDEX `fk_chatmember_pmember1_idx` (`member_no` ASC),
  PRIMARY KEY (`no`, `member_no`),
  CONSTRAINT `fk_chatmember_pmember1`
    FOREIGN KEY (`member_no`)
    REFERENCES `mydb`.`member` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvc3`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc3`.`chat` (
  `content` VARCHAR(45) NOT NULL,
  `lastinputTime` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `chatmember_no` INT NOT NULL,
  `chatmember_member_no` INT NOT NULL,
  INDEX `fk_chat_chatmember1_idx` (`chatmember_no` ASC, `chatmember_member_no` ASC),
  CONSTRAINT `fk_chat_chatmember1`
    FOREIGN KEY (`chatmember_no` , `chatmember_member_no`)
    REFERENCES `mydb`.`chatmember` (`no` , `member_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
